name: action-test-2

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Print commit SHA (environment variable)
        run: |
            echo "The commit SHA is: $GITHUB_SHA"
            jq --version
            yq --version
      - name: Print commit SHA (context expression)
        run: |
            echo "The commit SHA from context is: ${{ github.sha }}"
            echo "The commit SHA from context is: ${GITHUB_SHA:0:7}"
            echo "The commit SHA from context is: ${{ github.sha }}:0:7"